'use client';
// src/app/(dashboard)/dashboard/settings/billing/page.tsx

import { useState, useEffect } from 'react';
import { ArrowLeft }           from 'lucide-react';
import { useRouter }           from 'next/navigation';
import toast                   from 'react-hot-toast';

import PageHeader from '@/components/ui/PageHeader';
import FormField  from '@/components/ui/FormField';
import Button     from '@/components/ui/Button';
import { Skeleton } from '@/components/ui/SkeletonTable';
import { useFetch }  from '@/hooks/useFetch';
import { apiCall }   from '@/lib/apiClient';
import type { TenantSettingsDetail } from '@/types';

export default function BillingSettingsPage() {
  const router = useRouter();
  const { data, loading } = useFetch<{ settings: TenantSettingsDetail }>('/api/tenant-settings');

  const [taxType,      setTaxType]      = useState<'SINGLE' | 'SPLIT'>('SINGLE');
  const [taxPercent,   setTaxPercent]   = useState('18');
  const [cgst,         setCgst]         = useState('9');
  const [sgst,         setSgst]         = useState('9');
  const [gstNumber,    setGstNumber]    = useState('');
  const [currency,     setCurrency]     = useState('INR');
  const [showGST,      setShowGST]      = useState(true);
  const [showStoreName, setShowStoreName] = useState(true);
  const [footerMsg,    setFooterMsg]    = useState('');
  const [lowStock,     setLowStock]     = useState('10');
  const [saving,       setSaving]       = useState(false);
  const [dirty,        setDirty]        = useState(false);

  useEffect(() => {
    const s = data?.settings;
    if (!s) return;
    setTaxType(s.taxType as 'SINGLE' | 'SPLIT');
    setTaxPercent(String(s.taxPercent));
    setCgst(String(s.cgst));
    setSgst(String(s.sgst));
    setGstNumber(s.gstNumber ?? '');
    setCurrency(s.currency);
    setShowGST(s.showGST);
    setShowStoreName(s.showStoreName);
    setFooterMsg(s.footerMessage ?? '');
    setLowStock(String(s.defaultLowStock));
  }, [data]);

  function mark() { setDirty(true); }

  async function handleSave() {
    setSaving(true);
    try {
      await apiCall('PUT', '/api/tenant-settings', {
        taxType,
        taxPercent:      Number(taxPercent),
        cgst:            Number(cgst),
        sgst:            Number(sgst),
        gstNumber:       gstNumber || null,
        currency,
        showGST,
        showStoreName,
        footerMessage:   footerMsg || null,
        defaultLowStock: Number(lowStock),
      });
      toast.success('Billing settings saved');
      setDirty(false);
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : 'Failed to save');
    } finally { setSaving(false); }
  }

  if (loading) return (
    <div className="max-w-2xl mx-auto space-y-4">
      {Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-12 rounded-xl" />)}
    </div>
  );

  return (
    <div className="max-w-2xl mx-auto">
      <button onClick={() => router.back()}
        className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-800 mb-5 transition-colors">
        <ArrowLeft size={15} /> Settings
      </button>
      <PageHeader title="Billing & Tax" subtitle="Applies to all bills and invoices generated by your business." />

      <div className="space-y-4">
        {/* GST */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 space-y-4">
          <h2 className="text-xs font-semibold uppercase tracking-wider text-gray-400">GST Configuration</h2>
          <FormField label="GST Number" hint="Leave blank if not GST registered.">
            <input value={gstNumber} onChange={e => { setGstNumber(e.target.value); mark(); }}
              placeholder="29AAACH7409R1ZZ" className="form-input" maxLength={50} />
          </FormField>

          <FormField label="Tax type">
            <div className="flex gap-3">
              {(['SINGLE', 'SPLIT'] as const).map(t => (
                <label key={t} className="flex items-center gap-2 cursor-pointer">
                  <input type="radio" checked={taxType === t}
                    onChange={() => { setTaxType(t); mark(); }}
                    className="text-indigo-600 focus:ring-indigo-500" />
                  <span className="text-sm text-gray-700">{t === 'SINGLE' ? 'Single rate (GST%)' : 'Split (CGST + SGST)'}</span>
                </label>
              ))}
            </div>
          </FormField>

          {taxType === 'SINGLE' ? (
            <FormField label="Tax %" hint="Applied to the taxable amount on every bill.">
              <input type="number" min="0" max="100" value={taxPercent}
                onChange={e => { setTaxPercent(e.target.value); mark(); }}
                className="form-input w-32" />
            </FormField>
          ) : (
            <div className="grid grid-cols-2 gap-4">
              <FormField label="CGST %">
                <input type="number" min="0" max="100" value={cgst}
                  onChange={e => { setCgst(e.target.value); mark(); }} className="form-input" />
              </FormField>
              <FormField label="SGST %">
                <input type="number" min="0" max="100" value={sgst}
                  onChange={e => { setSgst(e.target.value); mark(); }} className="form-input" />
              </FormField>
            </div>
          )}
        </div>

        {/* Display */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 space-y-4">
          <h2 className="text-xs font-semibold uppercase tracking-wider text-gray-400">Bill Display</h2>
          <FormField label="Currency code" hint="e.g. INR, USD, EUR">
            <input value={currency} onChange={e => { setCurrency(e.target.value.toUpperCase()); mark(); }}
              maxLength={5} className="form-input w-28" />
          </FormField>
          <div className="flex flex-col gap-3">
            <label className="flex items-center gap-2.5 cursor-pointer">
              <input type="checkbox" checked={showGST} onChange={e => { setShowGST(e.target.checked); mark(); }}
                className="rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" />
              <span className="text-sm text-gray-700">Show GST breakdown on bills</span>
            </label>
            <label className="flex items-center gap-2.5 cursor-pointer">
              <input type="checkbox" checked={showStoreName} onChange={e => { setShowStoreName(e.target.checked); mark(); }}
                className="rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" />
              <span className="text-sm text-gray-700">Show store name on bills</span>
            </label>
          </div>
          <FormField label="Footer message" hint="Printed at the bottom of every bill. Max 200 chars.">
            <input value={footerMsg} onChange={e => { setFooterMsg(e.target.value); mark(); }}
              placeholder="Thank you for visiting!" maxLength={200} className="form-input" />
          </FormField>
        </div>

        {/* Inventory */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5">
          <h2 className="text-xs font-semibold uppercase tracking-wider text-gray-400 mb-4">Inventory Alerts</h2>
          <FormField label="Default low-stock threshold" hint="Products below this quantity trigger a low-stock alert.">
            <input type="number" min="0" value={lowStock}
              onChange={e => { setLowStock(e.target.value); mark(); }} className="form-input w-28" />
          </FormField>
        </div>
      </div>

      <div className="flex justify-end gap-3 mt-5 pb-6">
        <Button variant="secondary" onClick={() => router.back()}>Cancel</Button>
        <Button onClick={handleSave} loading={saving} disabled={!dirty}>Save settings</Button>
      </div>
    </div>
  );
}
